### ISSUE TITLE
Module Not Found

### ISSUE THREAD

**Issue by NearRiver00** [miftakhlaziz/pengenalan_plat_nomor_otomatis#1]
Hi thank you for sharing this, i already test your program and running good in Knn_Training_dan_Testing. but when i trying to run Deteksi_Plat i get the probem

    from Kode_Sumber_Deteksi_Plat import Main_Deteksi_Plate
ModuleNotFoundError: No module named 'Kode_Sumber_Deteksi_Plat'

how can i solve this ?
Thank you

**Comment by zscoders** [comment]
Wait, i can solve this problem, but please follow me on GitHub thanks

Pada tanggal Sen, 14 Des 2020 14.46, NearRiver00 <notifications@github.com>
menulis:

**Comment by zscoders** [comment]
> Hi thank you for sharing this, i already test your program and running good in Knn_Training_dan_Testing. but when i trying to run Deteksi_Plat i get the probem
> 
> ```
> from Kode_Sumber_Deteksi_Plat import Main_Deteksi_Plate
> ```
> 
> ModuleNotFoundError: No module named 'Kode_Sumber_Deteksi_Plat'
> 
> how can i solve this ?
> Thank you

You can Call function Main_Deteksi_Plate from Directory Kode_Sumber_Deteksi_Plat

Thanks

**Comment by NearRiver00** [comment]
i already follow your account, so i only change this line :
from this line : 
from Kode_Sumber_Deteksi_Plate import Deteksi_Karakter
from Kode_Sumber_Deteksi_Plate import Deteksi_Plat 
to this line : 
Main_Deteksi_Plate from Directory Kode_Sumber_Deteksi_Plat

like that ? iam sorry a little bit confuse about that.

**Comment by zscoders** [comment]
> i already follow your account, so i only change this line :
> from this line :
> from Kode_Sumber_Deteksi_Plate import Deteksi_Karakter
> from Kode_Sumber_Deteksi_Plate import Deteksi_Plat
> to this line :
> Main_Deteksi_Plate from Directory Kode_Sumber_Deteksi_Plat
> 
> like that ? iam sorry a little bit confuse about that.

no sir, you just using the code

> from Kode_Sumber_Deteksi_Plate import Deteksi_Karakter
> from Kode_Sumber_Deteksi_Plate import Deteksi_Plat

and "Kode_Sumber_Deteksi_Plate" is a directory for save a function Deteksi_Karakter and Deteksi_Plat
so, if you use "Deteksi_Karakter and Deteksi_Plat" you can call this function from "Kode_Sumber_Deteksi_Plate"
